#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"

echo "-----> Creating mail service directory"
mkdir -p "$PLUGIN_DATA_ROOT"

echo "-----> Mail plugin installed successfully"
