name: CI

on:
  push:
    branches: [trunk, main, master]
  pull_request:
    branches: [trunk, main, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dokku
        run: |
          wget -NP . https://dokku.com/install/v0.35.15/bootstrap.sh
          sudo DOKKU_TAG=v0.35.15 bash bootstrap.sh

      - name: Install bats
        run: sudo apt-get update && sudo apt-get install -y bats

      - name: Install plugin
        run: sudo dokku plugin:install file://${{ github.workspace }} mail

      - name: Run integration tests
        run: make test-integration
